apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: burning-hoverfly-go 
  janus-idp.io/tekton: burning-hoverfly-go
  backstage.io/kubernetes-id: burning-hoverfly-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: burning-hoverfly-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  